In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Libraries imported successfully")

Libraries imported successfully

In [23]:
df=pd.read_csv("../data/retail_sales_dataset.csv")
df.head(5)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,24-11-2023,CUST001,Male,34,Beauty,3,50,150
1,2,27-02-2023,CUST002,Female,26,Clothing,2,500,1000
2,3,13-01-2023,CUST003,Male,50,Electronics,1,30,30
3,4,21-05-2023,CUST004,Male,37,Clothing,1,500,500
4,5,06-05-2023,CUST005,Male,30,Beauty,2,50,100

In [24]:
df.shape

(1000, 9)

In [25]:
df.tail(5)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,16-05-2023,CUST996,Male,62,Clothing,1,50,50
996,997,17-11-2023,CUST997,Male,52,Beauty,3,30,90
997,998,29-10-2023,CUST998,Female,23,Beauty,4,25,100
998,999,05-12-2023,CUST999,Female,36,Electronics,3,50,150
999,1000,12-04-2023,CUST1000,Male,47,Electronics,4,30,120

In [26]:
df.columns.tolist()

['Transaction ID',
 'Date',
 'Customer ID',
 'Gender',
 'Age',
 'Product Category',
 'Quantity',
 'Price per Unit',
 'Total Amount']

In [27]:
df.dtypes

Transaction ID      int64
Date                  str
Customer ID           str
Gender                str
Age                 int64
Product Category      str
Quantity            int64
Price per Unit      int64
Total Amount        int64
dtype: object

In [28]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [29]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [32]:
df["Date"]=pd.to_datetime(df["Date"])
df["Date"].dtype

C:\Users\joelt\AppData\Local\Temp\ipykernel_14212\113833280.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date"]=pd.to_datetime(df["Date"])

dtype('<M8[us]')

In [33]:
df["Date"]=pd.to_datetime(
    df["Date"],
    format="%d-%m-%y"
)
print(df["Date"].dtype)
print(df["Date"].head())

datetime64[us]
0   2023-11-24
1   2023-02-27
2   2023-01-13
3   2023-05-21
4   2023-05-06
Name: Date, dtype: datetime64[us]

In [34]:
df.describe()

,Transaction ID,Date,Age,Quantity,Price per Unit,Total Amount
count,1000.000000,1000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,2023-07-03 00:25:55.200000,41.39200,2.514000,179.890000,456.000000
min,1.000000,2023-01-01 00:00:00,18.00000,1.000000,25.000000,25.000000
25%,250.750000,2023-04-08 00:00:00,29.00000,1.000000,30.000000,60.000000
50%,500.500000,2023-06-29 12:00:00,42.00000,3.000000,50.000000,135.000000
75%,750.250000,2023-10-04 00:00:00,53.00000,4.000000,300.000000,900.000000
max,1000.000000,2024-01-01 00:00:00,64.00000,4.000000,500.000000,2000.000000
std,288.819436,NaN,13.68143,1.132734,189.681356,559.997632

In [35]:
expected_amount=df["Quantity"]*df["Price per Unit"]
mismatch_count=(df["Total Amount"]!=expected_amount).sum()
print("Number of mismatched records: ",mismatch_count)

Number of mismatched records:  0

In [36]:
print("Minimum age: ",df["Age"].min())
print("Maximum age: ",df["Age"].max())
print("Invalid ages: ",((df["Age"]<0)|(df["Age"]>120)).sum())

Minimum age:  18
Maximum age:  64
Invalid ages:  0

In [37]:
print("Invalid quantities: ",(df["Quantity"]<=0).sum())
print("Invalid prices: ",(df["Price per Unit"]<=0).sum())

Invalid quantities:  0
Invalid prices:  0

In [38]:
print("Product categories: ")
print(df["Product Category"].unique())
print("\nNumber of unique categories: ",)
print(df["Product Category"].unique())

Product categories:
<StringArray>
['Beauty', 'Clothing', 'Electronics']
Length: 3, dtype: str

Number of unique categories:
<StringArray>
['Beauty', 'Clothing', 'Electronics']
Length: 3, dtype: str

In [39]:
df.to_csv("../data/retail_sales_cleaned.csv",index=False)
print("Prepared dataset saved successfully")

Prepared dataset saved successfully

In [40]:
df=pd.read_csv("../data/retail_sales_cleaned.csv")
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [41]:
print("Number of rows:",df.shape[0])
print("Number of columns:",df.shape[1])

Number of rows: 1000
Number of columns: 9

In [42]:
df.discribe()

AttributeError: 'DataFrame' object has no attribute 'discribe'

In [ ]:
df.describe()

In [ ]:
total_revanue=df["Total Amount"].sum()
print("Total Sales Revanue:",total_revanue)

In [ ]:
average_transaction=df["Total Amount"].mean()
print("Average transaction value:",round(average_transaction,2)

In [ ]:
average_trasaction=df["Total Amount"].mean()
print("Average transaction value:",round(average_transaction,2))

In [ ]:
average=df["Total Amount"].mean()
print("Average transaction value:", 
      round(average,2))

In [ ]:
category_revanue=df.groupby("Product Category")["Total Amount"].sum()
print(category_revanue)

In [ ]:
top_category=category_revanue.idmax()
top_revanue=category_revanue.max()
print("Highest revanue category:",top_category)
print("Total revanue:",top_revanue)

In [ ]:
top_category=category_revanue.idxmax()
top_revanue=category_revanue.max()
print("Highest revanue category:",top_category)
print("Total revanue:",top_revanue)

In [ ]:
total_quantity=df["Quantity"].sum()
print("Total quantity sold:",total_quantity)

In [ ]:
total_transactions=df["Transaction ID"].unique()
print("Total number of transactions:",total_transactions)

In [ ]:
average_quantity=df["Quantity"].mean()
print("Average quantity per transaction:",
      round(average_quantity,2))

In [ ]:
gender_revanue=df.groupby("Gender")["Total Amount"].sum()
print(gender_revanue)

In [ ]:
top_gender=gender_revanue.idxmax()
top_gender_revanue=gender_revanue.max()
print("Gender with highest revanue:",top_gender)
print("Total revanue:",top_gender_revanue)

In [ ]:
df["Age Group"]=pd.cut(
    df["Age"],
    bins=[17,25,35,45,55,65],
    labels=["18-25","26-35","36-45","46-55","56-65"]
)
age_group_revenue=df.groupby(
    "Age Group", observed=False
)["Total Amount"].sum()
print(age_group_revenue)

In [ ]:
top_age_group=age_group_revenue.idxmax()
top_age_revenue=age_group_revenue.max()
print("Age group with highest revenue:",top_age_group)
print("Total revenue:",top_age_revenue)

In [ ]:
df["Month"]=df["Date"].dt.to_period("M")
monthly_revenue=df.groupby("Month")["Total Amount"].sum()
print(monthly_revenue)

In [ ]:
df=["Month"]=df["Date"].dt.to_period("M")
monthly_revenue=df.groupby("Month")["Total Amount"].sum()
print(monthly_revenue)

In [ ]:
df["Date"]=pd.to_datetime(
    df["Date"],
    format="%d-%m-%y"
)
print(df["Date"].dtype)
df=["Month"]=df["Date"].dt.to_period("M")
monthly_revenue=df.groupby("Month")["Total Amount"].sum()
print(monthly_revenue)

In [ ]:
df["Date"]=pd.to_datetime(
    df["Date"],
    format="%d-%m-%y"
)
print(df["Date"].dtype)

In [ ]:
df["Date"]=pd.to_datetime(
    df["Date"],
    format="%d-%m-%Y"
)
print(df["Date"].dtype)

In [ ]:
print(df["Date"].head())
print(df["Date"].tail())

In [ ]:
df["Date"]=pd.to_datetime(
    df["Date"],
    format="%Y-%m-%d"
)
print(df["Date"].dtype)

In [ ]:
df["Month"]=df["Date"].dt.to_period("M")
monthly_revenue=df.groupby("Month")["Total Amont"].sum()
print(monthly_revenue)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("../data/retail_sales_cleaned.csv")
df["Date"]=pd.to_datetime(df["Date"])
print(df.head())

In [ ]:
df["Month"]=df["Date"].dt.to_period("M")
monthly_revenue=df.groupby("Month")["Total Amount"].sum()
print(monthly_revenue)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("../data/retail_sales_cleaned.csv")
df["Date"]=pd.to_datetime(df["Date"])
monthly_revenue=df.groupby(
    df["Date"].dt.to_period("M")
)["Total Amount"].sum()
monthly_revenue.plot(kind="line",marker="o")
plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.savefig("../visualizations/monthly_revenue.png")
plt.show()

In [ ]:
category_revenue=df.group("Product Category")["Total Amount"].sum()
category_revenue.plot(kind="bar")
plt.title("Revenue by Product Category")
plt.xlabel("Product Category")
plt.ylabel("Total Revanue")
plt.xtricks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
category_revenue=df.groupby("Product Category")["Total Amount"].sum()
category_revenue.plot(kind="bar")
plt.title("Revenue by Product Category")
plt.xlabel("Product Category")
plt.ylabel("Total Revanue")
plt,xtricks(rotation=45)
plt.tight_layout()
plt.savefig("../visualizations/revenue_by_category.png")
plt.show()

In [ ]:
gender_revenue=df.groupby("Gender")["Total Amount"].sum()
gender_revenue.plot(kind="bar")
plt.title("Revenue by Gender")
plt.xlabel("Gender")
plt.ylabel("Total Revenue")

In [ ]:
gender_revenue=df.groupby("Gender")["Total Amount"].sum()
gender_revenue.plot(kind="bar")
plt.title("Revenue by Gender")
plt.xlabel("Gender")
plt.ylabel("Total Revenue")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("../visualizations/revenue_by_gender.png")
plt.show()

In [ ]:
age_bins=[0,20,30,40,50,60,100]
age_labels=["Under 20", "20-30", "31-40", "41-50", "51-60", "Above 60"]
df["Age Group"]=pd.cut(
    df["Age"],
    bins=age_bins,
    labels=age_labels,
    include_lowest=True
)
age_revenue=df.groupby(
    "Age Group",observed=False
)["Total Amount"].sum()
age_revenue.plot(kind="bar")
plt.title("Revenue by Age Group")
plt.xlabel("Age Group")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("../visualizations/revenue_by_age_group.png")
plt.show()

In [ ]:
tottal_revenue=df["Total Amount"].sum()
total_transactions=df["Transaction ID"].nunique()
total_quantity=df.groupby("Transaction ID")["Total Amount"].sum().mean()
print(Total Revenue:", total_revenue)
print("Total Transactions:", total_transactions)
print("Total Items Sold:",total_quantity)
print("Average Transaction Value:",
      round(average_transcation,2))

In [ ]:
tottal_revenue=df["Total Amount"].sum()
total_transactions=df["Transaction ID"].nunique()
total_quantity=df.groupby("Transaction ID")["Total Amount"].sum().mean()
print("Total Revenue:", total_revenue)
print("Total Transactions:", total_transactions)
print("Total Items Sold:",total_quantity)
print("Average Transaction Value:",
      round(average_transcation,2))

In [ ]:
total_revenue=df["Total Amount"].sum()
total_transactions=df["Transaction ID"].nunique()
total_quantity=df.groupby("Transaction ID")["Total Amount"].sum().mean()
print("Total Revenue:", total_revenue)
print("Total Transactions:", total_transactions)
print("Total Items Sold:",total_quantity)
print("Average Transaction Value:",
      round(average_transcation,2))

In [ ]:
total_revenue=df["Total Amount"].sum()
total_transactions=df["Transaction ID"].nunique()
total_quantity=df["Quantity"].sum()
average_transcation=df.groupby("Transaction ID")["Total Amount"].sum().mean()
print("Total Revenue:", total_revenue)
print("Total Transactions:", total_transactions)
print("Total Items Sold:",total_quantity)
print("Average Transaction Value:",
      round(average_transcation,2))

In [ ]:
df.to_csv("../data/retail_sales_cleaned.csv",
          index=False)
print("Cleaned dataset saved successfully")

In [ ]:
df.to_excel("../data/retail_sales_cleaned.xlsx",
            index=False)
print("Excel file saved successfully")

In [ ]:
print("RETAIL SALES ANALYSIS SUMMARY")
print("---------------------------------")
print("Total Revenue:",df["Total Amount"].sum())
print("Total Transactions:",df["Transaction ID"].unique())
print("Total Items Sold:",df["Quantity"].sum())
print("Product Categories:",df["Product Category"].unique())
print("Customer Count:",df["Customer ID"].unique())

In [ ]:
plt.savefig("../visualizations/monthly_revenue_trend.png")

In [43]:
print("Hello")

Hello

In [44]:
print(df.shape)

(1000, 9)

In [45]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
df.dtypes

Transaction ID      int64
Date                  str
Customer ID           str
Gender                str
Age                 int64
Product Category      str
Quantity            int64
Price per Unit      int64
Total Amount        int64
dtype: object

In [48]:
print(df["Date"].dtype)

str

In [50]:
df["Date"]=pd.to_datetime(df["Date"])

In [52]:
print(df["Date"].dtype)

datetime64[us]

In [53]:
(df["Quantity"]*df["Price per Unit"]==df["Total Amount"]).sum()

np.int64(1000)

In [54]:
print("Invalid quantites:",(df["Quantity"]<=0).sum())
print("Invalid prices:",(df["Price per Unit"]<=0).sum())
print("Invalid ages:",((df["Age"]<0)|(df["Age"]>120)).sum())

Invalid quantites: 0
Invalid prices: 0
Invalid ages: 0

In [56]:
df.to_csv("../data/retail_sales_cleaned.csv",index=False)

In [57]:
monthly_revenue=df.groupby(
    df["Date"].dt.to_period("M")
)["Total Amount"].sum()
print(monthly_revenue)

Date
2023-01    35450
2023-02    44060
2023-03    28990
2023-04    33870
2023-05    53150
2023-06    36715
2023-07    35465
2023-08    36960
2023-09    23620
2023-10    46580
2023-11    34920
2023-12    44690
2024-01     1530
Freq: M, Name: Total Amount, dtype: int64

500

<class 'int'>
<class 'float'>
<class 'str'>